spring.application.name=objetos-perdidos-backend

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.qzqvvdnjizhaewbizoit
spring.datasource.password=6EoRqtcwdvBsU3Kt

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

server.port=8080
supabase.issuer-uri=https://qzqvvdnjizhaewbizoit.supabase.co/auth/v1
# Configurar el issuer de Supabase para validar los tokens Bearer
# supabase.issuer-uri=https://<project-ref>.supabase.co