spring.application.name=objetos-perdidos-backend

spring.datasource.url=${jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres}
spring.datasource.username=${postgres.qzqvvdnjizhaewbizoit}
spring.datasource.password=${lu201206ciana_}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

server.port=${PORT:8080}

supabase.issuer-uri=${https://qzqvvdnjizhaewbizoit.supabase.co/auth/v1}