spring.application.name=objetos-perdidos-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres.qzqvvdnjizhaewbizoit}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

server.port=${PORT:8080}

supabase.issuer-uri=${SUPABASE_ISSUER_URI:https://qzqvvdnjizhaewbizoit.supabase.co/auth/v1}